protected/models/Category.php
<?php

/**
 * This is the model class for table "category".
 *
 * The followings are the available columns in table 'category':
 * @property integer $id
 * @property string $title
 * @property string $url
 * @property string $url_rss

 * @property integer $deleted
 * @property integer $active

 * @property string $created_at
 *
 * The followings are the available model relations:
 * @property News[] $news
 * @property PostQueue[] $postQueues
 * @property SubCategories[] $Subcategory
 */
class Category extends BaseModels
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'category';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title, url,created_at', 'required'),
			array('deleted, active', 'numerical', 'integerOnly'=>true),
			array('title, url', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, title,url_rss, url, deleted, active, created_at,pagination_size', 'safe'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'news' => array(self::HAS_MANY, 'News', 'category_id'),
			'postQueues' => array(self::HAS_MANY, 'PostQueue', 'catgory_id'),
			'Subcategory' => array(self::HAS_MANY, 'SubCategories', 'category_id'),
			'Settings' => array(self::HAS_MANY, 'Settings', 'category_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		$array = array(
			'id' => 'ID',
			'title' => 'Title',
			'url' => 'Url',
			'is_rss' => 'Is Rss',
			'deleted' => 'Deleted',
			'shorten_url' => 'shorten url',
			'active' => 'Status',
			'created_at' => 'Created At',
		);
		return array_merge($array,$this->Labels());
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		if(isset($this->pagination_size))
			$pages = $this->pagination_size;
		else
			$pages=5;

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('url',$this->url,true);

		$criteria->compare('deleted',0);
		$criteria->compare('active',$this->active);

		$criteria->compare('created_at',$this->created_at,true);

		$criteria->order = 'title asc';
		return new CActiveDataProvider($this, array(
			'pagination' => array('pageSize' => $pages),
			'criteria'=>$criteria,
		));
	}


	public function get_category($order= true){

		$criteria=new CDbCriteria;
		if($order)
		$criteria->order = 'title asc';
		return $this->findAll($criteria);
	}


	public function generateTree()
	{
		$data = array();

		foreach ($this->findAll() as $category) {
			$data[$category->id] = array(
				'id'   => $category->id,
				'text' => '<a href="/admin/catalog/category/id/'.$category->id.'">'.$category->title.'</a>',

			);
			foreach ($category->Subcategory as $item) {
				$data[$category->id]['children'][$item->id] = array(
					'id'   => $item->id,
					'text' =>  '<a href="/admin/catalog/item/id/'.$item->id.'">'.$item->title.'</a>',
					'expanded' => false,
				);
			}

		}
		return $data;
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Category the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	public function getNextId() {
		$record = self::model()->find(array(
			'condition' => 'id>:current_id',
			'order' => 'id ASC',
			'limit' => 1,
			'params' => array(':current_id' => $this->id),
		));
		if ($record !== null) {
			return $record;
		}
		return null;
	}
	public function getPreviousId() {
		$record = self::model()->find(array(
			'condition' => 'id<:current_id',
			'order' => 'id DESC',
			'limit' => 1,
			'params' => array(':current_id' => $this->id),
		));
		if ($record !== null) {
			return $record;
		}
		return null;
	}
}

protected/controllers/CategoryController.php
<?php
class CategoryController extends BaseController
{



	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(

			array('allow',
				'actions'=>array('admin','delete','create','update','index','view','status','edit'),
				'users'=>array(Yii::app()->user->getState('type')),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{


		$subSections = new SubCategories();
		$subSections->category_id=$id;

		$news_table = new News();
		$news_table->category_id=$id;


		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'sub_Sections'=>$subSections,
			'news_table'=>$news_table,
		));

	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Category;

		// Uncomment the following line if AJAX validation is needed

		$this->performAjaxValidation($model);

		if(isset($_POST['Category']))
		{
			$model->attributes=$_POST['Category'];
			$model->created_at = date('Y-m-d H:i:s');
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function actionEdit(){
		if(isset($_POST)){
			if(isset($_POST['name']) && isset($_POST['value']) && isset($_POST['pk']) && isset($_POST['scenario'])){
				$model = $this->loadModel($_POST['pk']);

				if(!empty($_POST['name'])){
					$name = $_POST['name'];
					$value = $_POST['value'];
					$model->$name = $value;
					if($model->save())
						echo true;
					else
						echo false;
				}
			}

		}
	}

	public function actionStatus($id)
	{


		$model=$this->loadModel($id);

		if($model->active == 0){
			$model->active =1;
		}else{
			$model->active =0;
		}
		// Uncomment the following line if AJAX validation is needed




  			if($model->save()) {
				$this->redirect(array('admin','id'=>$model->id));

			}


	}
	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Category']))
		{
			$model->attributes=$_POST['Category'];
			$model->created_at = date('Y-m-d H:i:s');
			if($model->save()) {
				Yii::app()->user->setFlash('update', 'Thank you for add conetns ... . .... ');
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$data  = $this->loadModel($id);

		$data->deleted = 1;

		$data->save();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{

		$model=new Category('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Category']))
			$model->attributes=$_GET['Category'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Category('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Category'])) {
			$this->data_search = $_GET['Category'];
			$this->data_search($model);
			$model->attributes = $_GET['Category'];
		}
		$this->render('admin',array(
			'model'=>$model,
		));
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Category the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Category::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Category $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='category-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/category/_form.php
<?php
/* @var $this CategoryController */
/* @var $model Category */
/* @var $form TbActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('booster.widgets.TbActiveForm', array(
	'id'=>'category-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>true,
	'type' => 'horizontal',

)); ?>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'title'); ?>
	<?php echo $form->textFieldGroup($model,'url'); ?>



 	<div class="col-sm-12">
<div class="col-sm-5">
	<div class="col-sm-2  col-sm-offset-7"  style="margin-top:10px;">
</div>
	<div class="col-sm-3  col-sm-pull-1">
	<?php echo $form->checkboxGroup($model,'active'); ?>
		</div>
</div>
		</div>
	<div class="form-actions  pull-right" style="margin-bottom: 20px">
		<?php $this->widget(
			'booster.widgets.TbButton',
			array(
				'buttonType' => 'submit',
				'context' => 'primary',
				'label' => $model->isNewRecord ? 'Create' : 'Save'
			)
		); ?>


	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/category/_search.php
<?php
/* @var $form TbActiveForm */
$form=$this->beginWidget('booster.widgets.TbActiveForm', array(
    'action'=>Yii::app()->createUrl($this->route),
    'method'=>'get',
    'id'=>'form-visible',
)); ?>

    <div class="col-sm-2">
        <?php echo $form->textFieldGroup(
            $model,
            'id',
            array(
                'prepend' => $form->checkboxGroup(
                    $model,
                    'visible_id',
                    array(
                        'inline'=>true,
                        //'labelOptions'=>array('class'=>'btn btn-primary'),
                        'widgetOptions'=>array(
                            'htmlOptions'=>array(
                                // 'style'=>'opacity: 0;'
                            ),
                        ),
                    )
                ),
                'widgetOptions'=>array(

                    'htmlOptions'=>array(

                        'disabled'=>$model->visible_id?false:true
                    )
                ),
                'hint'=>''
            )
        ); ?>

    </div>
    <div class="col-sm-2">
        <?php echo $form->dropDownListGroup(
            $model,
            'title',
            array(
                'prepend' => $form->checkboxGroup(
                    $model,
                    'visible_title',
                    array(
                        'inline'=>true,
                        //'labelOptions'=>array('class'=>'btn btn-primary'),
                        'widgetOptions'=>array(
                            'htmlOptions'=>array(
                               // 'style'=>'opacity: 0;'
                            ),
                        ),
                    )
                ),
                'widgetOptions'=>array(
                    'data'=>array_merge(array(''=>'Choose one'),CHtml::listData(Category::model()->findAll('deleted=0'),'title','title')),
                    'htmlOptions'=>array(

                        'disabled'=>$model->visible_title?false:true
                    )
                ),
                'hint'=>''
            )
        ); ?>

    </div>
    <div class="col-sm-2">
        <?php echo $form->textFieldGroup(
            $model,
            'url',
            array(
                'prepend' => $form->checkboxGroup(
                    $model,
                    'visible_url',
                    array(
                        'inline'=>true,
                        //'labelOptions'=>array('class'=>'btn btn-primary'),
                        'widgetOptions'=>array(
                            'htmlOptions'=>array(
                                // 'style'=>'opacity: 0;'
                            ),
                        ),
                    )
                ),
                'widgetOptions'=>array(
                     'htmlOptions'=>array(

                        'disabled'=>$model->visible_url?false:true
                    )
                ),
                'hint'=>''
            )
        ); ?>

    </div>

    <div class="col-sm-2">
        <?php echo $form->dropDownListGroup(
            $model,
            'active',
            array(
                'prepend' => $form->checkboxGroup(
                    $model,
                    'visible_active',
                    array(
                        'inline'=>true,
                         'widgetOptions'=>array(
                            'htmlOptions'=>array(
                             ),
                        ),
                    )
                ),
                'widgetOptions'=>array(
                    'data'=>array_merge(array(''=>'All status'),array('0'=>'Disabled','1'=>'Active')),
                    'htmlOptions'=>array(
                        'disabled'=>$model->visible_active?false:true
                    )
                ),
                'hint'=>''
            )
        ); ?>

    </div>
    <div class="col-sm-2">
        <?php echo $form->datePickerGroup(
            $model,
            'created_at',
            array(
                'prepend' => $form->checkboxGroup(
                    $model,
                    'visible_created_at',
                    array(
                        'inline'=>true,
                         'widgetOptions'=>array(
                            'htmlOptions'=>array(
                             ),
                        ),
                    )
                ),
                'widgetOptions'=>array(
                    'options' => array(
                        'language' => 'en',
                        'format' => 'yyyy-mm-dd',
                        'viewformat' => 'yyyy-mm-dd',
                    ),

                    'htmlOptions'=>array(
                        'disabled'=>$model->visible_created_at?false:true
                    )
                ),
                'hint'=>''
            )
        ); ?>

    </div>
    <div class="col-sm-2 pull-left page-sizes"  >

        <?php echo $form->dropDownListGroup(
            $model,
            'pagination_size',
            array(

                'widgetOptions'=>array(
                    'data'=>$model->pages_size(),
                    'htmlOptions'=>array(

                    ),
                ),
                'hint'=>''
            )
        ); ?>
</div>




<?php $this->endWidget(); ?>

protected/views/category/admin.php
<?php
/* @var $this CategoryController */
/* @var $model Category */
/* @var $form TbActiveForm */

$this->pageTitle = "Sections | Admin";

$this->breadcrumbs=array(
	'sections'=>array('admin'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Category', 'url'=>array('index')),
	array('label'=>'Create Category', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('#form-visible').change(function(){
	$(this).submit();
	return true;
});
$('.search-form form').submit(function(){
	$('#category-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
/*$(\"input[name='Category[title]']\").attr('class','form-control');

$(\"select[name='Category[active]']\").attr('class','form-control');*/
");
?>

<section class="content">
	<div class="row">
		<div class="col-sm-12">
			<div class="box box-info">
				<div class="box-header with-border">
					<div class="col-sm-12 pull-right">
						<?php echo Yii::app()->params['statement']['previousPage']; ?>
					</div>
				</div>
				<div class="box-body">

					<?PHP //echo $this->renderPartial('_search',array('model'=>$model),true) ?>
					<?PHP

					$form=$this->beginWidget('booster.widgets.TbActiveForm', array(
						'action'=>Yii::app()->createUrl($this->route),
						'method'=>'get',
						'id'=>'form-visible',
					));
					?>
					<div class="col-sm-2 pull-left page-sizes"  >

						<?php echo $form->dropDownListGroup(
							$model,
							'pagination_size',
							array(

								'widgetOptions'=>array(
									'data'=>$model->pages_size(),
									'htmlOptions'=>array(

									),
								),
								'hint'=>''
							)
						); ?>
					</div>
					<?php
					$this->endWidget();

				/*	$this->widget('CTreeView', array('data' => $model->generateTree(),'persist'=>'cookie'));*/

					$this->widget('booster.widgets.TbGridView', array(
						'id'=>'category-grid',
						'type' => 'striped bordered condensed',
						'template' => '{items}{pager}{summary}',
						'enablePagination' => true,
						'pager' => array(
							'class' => 'booster.widgets.TbPager',
							'nextPageLabel' => 'Next',
							'prevPageLabel' => 'Previous',
							'htmlOptions' => array(
								'class' => 'pull-right',
								'filterClass'=>'asdasdasd',
							),

						),
						'htmlOptions' => array(
							'class' => 'table-responsive'
						),
							'filter' => $model,



						'dataProvider' => $model->search(),

						 /*'filterCssClass' => 'mohammad salahat',*/
						 /*'filterPosition' => 'header',// header / footer // body*/

						'columns' => array(
							/*array(
								'name'=>'id',
								'visible'=>$model->visible_id?true:false,
							),*/
							array(
								'name'=>'url',
								'type'=>'raw',
								'value'=>'CHtml::link($data->url,$data->url,array(\'target\'=>\'_blank\'))',
								'visible'=>$model->visible_url?true:false,

							),
 							/*array(
								'name'=>'title',
								'type'=>'raw',
								'value'=>'CHtml::link($data->title,$data->url,array(\'target\'=>\'_blank\'))',
								'visible'=>$model->visible_title?true:false,
							),*/

							array(
								'class' => 'booster.widgets.TbEditableColumn',
								'name' => 'title',
								'sortable' => true,
								'editable' => array(
									'url' => $this->createUrl('category/edit'),
									'placement' => 'right',
									'inputclass' => 'span1'
								),
								'visible'=>$model->visible_title?true:false,

							),

							array(
								'class' => 'booster.widgets.TbEditableColumn',
								'filter'=>array_merge(array(''=>'All status'),array('0'=>'Disabled','1'=>'Active')),
								'name' => 'active',
								'sortable' => true,
								'editable' => array(
									'type' => 'select2',
									'url' => $this->createUrl('category/edit'),
									'source' => array('0'=>'Disabled','1'=>'Active'),
									'placement' => 'right',
									'inputclass' => 'span1'
								),
								'type'=>'raw',
								'value'=>'$data->active?CHtml::tag("span",array("class"=>"label label-success"),"Active",true):CHtml::tag("span",array("class"=>"label label-danger"),"Disabled",true)',
								'visible'=>$model->visible_title?true:false,
							),
							/*array(
								'type'=>'raw',
								'name'=>'active',
								'filter'=>array_merge(array(''=>'All status'),array('0'=>'Disabled','1'=>'Active')),
								 'value'=>'$data->active?CHtml::tag("span",array("class"=>"label label-success"),"Active",true):CHtml::tag("span",array("class"=>"label label-danger"),"Disabled",true)',
								'visible'=>$model->visible_active?true:false,
							),*/
                            /*
							array(
								'name'=>'created_at',
								'visible'=>$model->visible_created_at?true:false,
							),*/
 							array(
								'class' => 'booster.widgets.TbButtonColumn',
								'header' => 'Options',
								//'template' => '{view}{update}{delete}{activate}{deactivate}',
								'template' => '{view}{delete}{activate}{deactivate}',
								'buttons' => array(
									'view' => array(
										'label' => 'View',
										'icon' => 'fa fa-eye',
									),
									'update' => array(
										'label' => 'Update',
										'icon' => 'fa fa-pencil-square-o',
									),
									'delete' => array(
										'label' => 'Delete',
										'icon' => 'fa fa-times',
									),

									'activate' => array(
										'label' => 'Deactivate',
										'url' => 'Yii::app()->createUrl(Yii::app()->controller->id."/status", array("id"=>$data->id))',
										'icon' => 'fa fa-toggle-off',
										'visible' => '$data->active == 1',
										'click' => "function(){

				$.fn.yiiGridView.update('category-grid', {  //change my-grid to your grid's name
				type:'POST',
				url:$(this).attr('href'),
				success:function(data) {
				$.fn.yiiGridView.update('category-grid');}});return false;}",
									),
									'deactivate' => array(
										'label' => 'Activate',
										'url' => 'Yii::app()->createUrl(Yii::app()->controller->id."/status", array("id"=>$data->id))',
										'icon' => 'fa fa-toggle-on',
										'visible' => '$data->active == 0',
										'click' => "function(){
				$.fn.yiiGridView.update('category-grid', {  //change my-grid to your grid's name
				type:'POST',
				url:$(this).attr('href'),
				success:function(data) {
				$.fn.yiiGridView.update('category-grid');}});return false;}"
									),

								)
							),
						))

					);?>
					<style>
						.checkbox {
							display: block;
							min-height: 0px;
							margin-top: 4px;
							margin-bottom: 0px;
							padding-left: 17px;
						}
						.input-group-addon input[type=radio], .input-group-addon input[type=checkbox] {
							margin-top: 0;
						}
						.radio input[type=radio], .radio-inline input[type=radio], .checkbox input[type=checkbox], .checkbox-inline input[type=checkbox] {
							float: left;
							margin-left: -16px;
						}
					</style>



				</div>

			</div>
		</div>
	 </div>
</section>

<!--Tour-->
<?php
$createLink = Yii::app()->createUrl('postQueue/main',array('#' => 'guider=eleven'));

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'firstSection',
		'title'        => 'Title',
		'next'         => 'second',
		'buttons'      => array(
			array('name'=>'Previous','classString' => 'tourcolor','onclick'=> "js:function(){  document.location = '$createLink';}"),

			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'Title of the section and when clicked it render you to section location on the site',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#category-grid_c0',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'second',
		'title'        => 'Active',
		'next'         => 'third',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('firstSection');}"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'The status of that section if it is set to active it will generate posts from that url if it is not set to active it will not generate posts from there',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '#category-grid_c1',
		'position'      => 1,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'third',
		'title'        => 'Option view',
		'next'         => 'fourth',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('second');}"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'View this item alone',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '.fa-eye',
		'position'      => 9,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'fourth',
		'title'        => 'Option edit',
		'next'         => 'fifth',
		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('third');}"
			),
			array(
				'name'   => 'Next',

			),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'update this item',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '.fa-pencil-square-o',
		'position'      => 9,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<?php
$continueTour = Yii::app()->createUrl('postQueue/main',array('#' => 'guider=twelve'));

$this->widget('ext.eguiders.EGuider', array(
		'id'           => 'fifth',
		'title'        => 'Option remove',

		'buttons'      => array(
			array(
				'name'   => 'Previous',
				'onclick'=> "js:function(){guiders.hideAll(); $('.highlight pre').hide(); guiders.show('fourth');}"
			),

			array('name'=>'Continue ','classString' => 'tourcolor','onclick'=> "js:function(){  document.location = '$continueTour';}"),

			array(
				'name'   => 'Exit',
				'onclick'=> "js:function(){guiders.hideAll();}"
			)
		),
		// why not call renderPartial to get the content of the Guide ? .. yeah, why not ?
		'description'   => 'Delete this item',
		'overlay'       => true,
		// you can attach your guide to any element in the page thanks to JQuery selectors
		'attachTo'      => '.fa-times',
		'position'      => 9,
		'xButton'       => true,
		'onShow'        => 'js:function(){ $(".highlight pre").show();}',
		'closeOnEscape' => true,
	)
);
?>
<!--endTour-->

protected/views/category/create.php
<?php
/* @var $this CategoryController */
/* @var $model Category */

$this->pageTitle = "Sections | Create";

$this->breadcrumbs = array(
    'sections' => array('admin'),
    'Create',
);
$this->menu = array(
    array('label' => 'List Category', 'url' => array('index')),
    array('label' => 'Manage Category', 'url' => array('admin')),
);
?>
<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <div class="col-sm-12 pull-right">
                       <?php echo Yii::app()->params['statement']['previousPage']; ?>
                            <?PHP
                            $this->widget(
                                'booster.widgets.TbButtonGroup',
                                array(
                                    'size' => 'small',
                                    'context' => 'info',
                                    'buttons' => array(
                                        array(
                                            'label' => 'Action',
                                            'items' => array(
                                                array('label' => 'Create', 'url' => array('create')),
                                                array('label' => 'Manage', 'url' => array('admin'))
                                            )
                                        ),
                                    ),
                                )
                            );
                            ?>

                    </div>
                </div>
                <div class="box-body">
                    <?php $this->renderPartial('_form', array('model' => $model)); ?>
                </div>
            </div>
        </div>
</section>